spring:

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_test?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Having21325!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop  # SessionFactory가 시작될 때 Drop, Create, Alert / 종료될 때 Drop 진행
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.havving: DEBUG

jwt:
  header: Authorization
  # HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

#sentry:
#  dsn: https://e3232d89a1634e93aabb93c94b291ac6@o981935.ingest.sentry.io/5936521